services:
    app:
        build:
            args:
                user: matheus
                uid: 1000
            context: ./
            dockerfile: docker/docker-compose/php/php.dockerfile
        image: php83
        extra_hosts:
            - host.docker.internal:host-gateway
        container_name: ${APP_NAME:-php}-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/docker-compose/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/docker-compose/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/docker-compose/php/.bashrc:/home/matheus/.bashrc
        networks:
            - dev

    nginx:
        image: nginx:alpine
        container_name: ${APP_NAME:-web}-nginx
        restart: unless-stopped
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www
            - ./docker/docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - dev
        links:
            - app

    db:
        image: postgres:14-alpine
        restart: unless-stopped
        container_name: ${APP_NAME:-postgres}-db
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD:-123456789}
            POSTGRES_DB: ${DB_DATABASE:-DB_PC}
            POSTGRES_USER: ${DB_USERNAME:-postgres}
        ports:
            - "${DB_PORT:-5432}:${DB_PORT:-5432}"
        volumes:
            - /home/dime/postgresdb14:/var/lib/postgresql/data
            - ./docker/docker-compose/postgres/01_estrutura_policia.sql:/docker-entrypoint-initdb.d/01_estrutura_policia.sql
            - ./docker/docker-compose/postgres/02_estrutura_seguranca.sql:/docker-entrypoint-initdb.d/02_estrutura_seguranca.sql
            - ./docker/docker-compose/postgres/03_dados.sql:/docker-entrypoint-initdb.d/03_dados.sql
        networks:
            - dev

networks:
    dev:
        driver: bridge
